apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongodb-root-username: cm9vdA== # base64 encoded 'root'
  mongodb-root-password: cGFzc3dvcmQ= # base64 encoded 'password'
